/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['email.js']) {
  _$jscoverage['email.js'] = [];
  _$jscoverage['email.js'][1] = 0;
  _$jscoverage['email.js'][3] = 0;
  _$jscoverage['email.js'][11] = 0;
  _$jscoverage['email.js'][12] = 0;
  _$jscoverage['email.js'][20] = 0;
  _$jscoverage['email.js'][23] = 0;
  _$jscoverage['email.js'][24] = 0;
  _$jscoverage['email.js'][26] = 0;
  _$jscoverage['email.js'][27] = 0;
  _$jscoverage['email.js'][28] = 0;
  _$jscoverage['email.js'][30] = 0;
  _$jscoverage['email.js'][33] = 0;
  _$jscoverage['email.js'][37] = 0;
  _$jscoverage['email.js'][41] = 0;
  _$jscoverage['email.js'][42] = 0;
}
_$jscoverage['email.js'][1]++;
var nodemailer = require("nodemailer");
_$jscoverage['email.js'][3]++;
var emailSettings = {service: "Gmail", auth: {user: "mr6r1n@gmail.com", pass: "1asd4ghj8QPP"}};
_$jscoverage['email.js'][11]++;
exports.sendInscriptionConfirmation = (function (user) {
  _$jscoverage['email.js'][12]++;
  var mailOptions = {from: "Witken - Inscription <inscritpion@witken.org>", to: user.email, subject: "Welcome to Witken", text: "Inscription stuff", html: generateMail(user)};
  _$jscoverage['email.js'][20]++;
  sendMail(mailOptions);
});
_$jscoverage['email.js'][23]++;
var sendMail = (function (mail) {
  _$jscoverage['email.js'][24]++;
  var smtpTransport = nodemailer.createTransport("SMTP", emailSettings);
  _$jscoverage['email.js'][26]++;
  smtpTransport.sendMail(mail, (function (error, response) {
  _$jscoverage['email.js'][27]++;
  if (error) {
    _$jscoverage['email.js'][28]++;
    console.log(error);
  }
  else {
    _$jscoverage['email.js'][30]++;
    console.log("Message sent: " + response.message);
  }
  _$jscoverage['email.js'][33]++;
  smtpTransport.close();
}));
});
_$jscoverage['email.js'][37]++;
var addAtachment = (function (mail, file) {
});
_$jscoverage['email.js'][41]++;
var generateMail = (function (user) {
  _$jscoverage['email.js'][42]++;
  return "<p>Hello</p>";
});
_$jscoverage['email.js'].source = ["var nodemailer = require('nodemailer');","","var emailSettings = {","    service: \"Gmail\",","    auth: {","        user: \"mr6r1n@gmail.com\",","        pass: \"1asd4ghj8QPP\"","    }","}","","exports.sendInscriptionConfirmation = function (user) {","    var mailOptions = {","        from: \"Witken - Inscription &lt;inscritpion@witken.org&gt;\",","        to: user.email,","        subject: \"Welcome to Witken\",","        text: \"Inscription stuff\",","        html: generateMail(user)","    }","    ","    sendMail(mailOptions);","}","","var sendMail = function (mail) {","    var smtpTransport = nodemailer.createTransport(\"SMTP\", emailSettings);","","    smtpTransport.sendMail(mail, function (error, response) {","        if (error) {","            console.log(error);","        } else {","            console.log(\"Message sent: \" + response.message);","        }","","        smtpTransport.close(); // shut down the connection pool, no more messages","    });","}","","var addAtachment = function(mail, file){","    ","}","","var generateMail = function(user){","    return '&lt;p&gt;Hello&lt;/p&gt;'","}"];
