/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['utils.js']) {
  _$jscoverage['utils.js'] = [];
  _$jscoverage['utils.js'][1] = 0;
  _$jscoverage['utils.js'][2] = 0;
  _$jscoverage['utils.js'][3] = 0;
  _$jscoverage['utils.js'][4] = 0;
  _$jscoverage['utils.js'][5] = 0;
  _$jscoverage['utils.js'][7] = 0;
  _$jscoverage['utils.js'][8] = 0;
  _$jscoverage['utils.js'][9] = 0;
  _$jscoverage['utils.js'][12] = 0;
  _$jscoverage['utils.js'][20] = 0;
  _$jscoverage['utils.js'][21] = 0;
  _$jscoverage['utils.js'][22] = 0;
  _$jscoverage['utils.js'][25] = 0;
  _$jscoverage['utils.js'][33] = 0;
  _$jscoverage['utils.js'][34] = 0;
  _$jscoverage['utils.js'][35] = 0;
  _$jscoverage['utils.js'][38] = 0;
  _$jscoverage['utils.js'][45] = 0;
  _$jscoverage['utils.js'][46] = 0;
  _$jscoverage['utils.js'][47] = 0;
  _$jscoverage['utils.js'][50] = 0;
  _$jscoverage['utils.js'][51] = 0;
  _$jscoverage['utils.js'][54] = 0;
}
_$jscoverage['utils.js'][1]++;
var sources = ["Input", "Database", "Server", "Route", "Unknown"];
_$jscoverage['utils.js'][2]++;
var levels = ["fatal", "warning", "info"];
_$jscoverage['utils.js'][3]++;
var fields = ["email", "pass", "general"];
_$jscoverage['utils.js'][4]++;
var databases = ["User", "Eventbrite", "Unknown"];
_$jscoverage['utils.js'][5]++;
var routes = ["Order confirmation", "Unknown"];
_$jscoverage['utils.js'][7]++;
exports.generateInputError = (function (field, message) {
  _$jscoverage['utils.js'][8]++;
  if (fields.indexOf(field) === -1) {
    _$jscoverage['utils.js'][9]++;
    field = "general";
  }
  _$jscoverage['utils.js'][12]++;
  return ({source: "Input", field: field, level: "Warning", error_message: message});
});
_$jscoverage['utils.js'][20]++;
exports.generateDatabaseError = (function (database, message) {
  _$jscoverage['utils.js'][21]++;
  if (databases.indexOf(database) === -1) {
    _$jscoverage['utils.js'][22]++;
    database = "Unknown";
  }
  _$jscoverage['utils.js'][25]++;
  return ({source: "Database", database: database, level: "Fatal", error_message: message});
});
_$jscoverage['utils.js'][33]++;
exports.generateServerError = (function (level, message) {
  _$jscoverage['utils.js'][34]++;
  if (levels.indexOf(level) === -1) {
    _$jscoverage['utils.js'][35]++;
    level = "warning";
  }
  _$jscoverage['utils.js'][38]++;
  return ({source: "Server", level: level, error_message: message});
});
_$jscoverage['utils.js'][45]++;
exports.generateRoutingError = (function (route, level, message) {
  _$jscoverage['utils.js'][46]++;
  if (routes.indexOf(route) === -1) {
    _$jscoverage['utils.js'][47]++;
    route = "Unknown";
  }
  _$jscoverage['utils.js'][50]++;
  if (levels.indexOf(level) === -1) {
    _$jscoverage['utils.js'][51]++;
    level = "warning";
  }
  _$jscoverage['utils.js'][54]++;
  return ({source: "Route", route: route, level: level, error_message: message});
});
_$jscoverage['utils.js'].source = ["var sources = ['Input', 'Database', 'Server', 'Route', 'Unknown'];","var levels = ['fatal', 'warning', 'info'];","var fields = ['email', 'pass', 'general'];","var databases = ['User', 'Eventbrite', 'Unknown'];","var routes = ['Order confirmation', 'Unknown'];","","exports.generateInputError = function(field, message){","    if(fields.indexOf(field)===-1){","        field = 'general';","    }","    ","    return {","        source: 'Input',        ","        field: field,","        level: 'Warning',","        error_message: message","    };","}","","exports.generateDatabaseError = function(database, message){","    if(databases.indexOf(database)===-1){","        database = 'Unknown';","    }","    ","    return {","        source: 'Database',","        database: database,","        level: 'Fatal',","        error_message: message","    };","}","","exports.generateServerError = function(level, message){","    if(levels.indexOf(level)===-1){","        level = 'warning';","    }","    ","    return {","        source: 'Server',","        level: level,","        error_message: message","    };","}","","exports.generateRoutingError = function(route, level, message){","    if(routes.indexOf(route)===-1){","        route = 'Unknown';","    }","    ","    if(levels.indexOf(level)===-1){","        level = 'warning';","    }","    ","    return {","        source: 'Route',","        route: route,","        level: level,","        error_message: message","    };","}"];
